### ISSUE TITLE
Add tags to docker images

### ISSUE THREAD

**Issue by peacock0803sz** [vim-denops/denops-dockerfile#10]
It would be better to tag the docker image, I propose 3 plans following:

## Plan A (Don't change image names)

Shortest, but could be mistaken for a vim/neovim image...

Format:

- `ghcr.io/vim-denops/vim:x.y.z` (latest will be `ghcr.io/vim-denops/vim`)
- `ghcr.io/vim-denops/neovim:x.y.z` (latest will be `ghcr.io/vim-denops/neovim`)

## Plan B (Same image name in Vim/Neovim)

A little redundant, but clear and same format as common docker images.

Format:

- `ghcr.io/vim-denops/denops:x.y.z-vim` (latest will be `ghcr.io/vim-denops/denops:vim`)
- `ghcr.io/vim-denops/denops:x.y.z-neovim` (latest will be `ghcr.io/vim-denops/denops:neovim`)

## Plan C (With suffixes, but different image names in Vim/Neovim)

Added `-vim` / `-neovim` prefixes, but I don't think it's a good one.

Format:

- `ghcr.io/vim-denops/vim-denops:x.y.z` (latest will be `ghcr.io/vim-denops/vim-denops`)
- `ghcr.io/vim-denops/neovim-denops:x.y.z` (latest will be `ghcr.io/vim-denops/neovim-denops`)

**Comment by peacock0803sz** [comment]
Let me know what you think @lambdalisue

**Comment by lambdalisue** [comment]
I think A should be enough.

**Comment by peacock0803sz** [comment]
Okay, I'll try to make it with Plan A...
